- name: Installing packages
  hosts: web
  become: yes # indicates become root user
  tasks:
    - name: installing packages using loops
      ansible.builtin.package:
        name: " {{ item }} "
        state: installed
      loop:
        - gcc
        - mysql
        - git
        - zip
