- name: filters examples
  hosts: local
  connection: local
  tasks: 
    - name: handle un-defined variable
      ansible.builtin.debug:
        msg: " Hello {{ person | default('Kumar') }} "
    
    - name: convert sring to list
      vars:
        fruits: " Apple, Bannana, Gauva " # string
      ansible.builtin.debug:
        msg: " Fruits are: {{ fruits | split(',') }} "
    
    - name: convert map into list
      vars:
        course:
          name: ansible
          duration: "15 hrs"
          student: Kumar
      ansible.builtin.debug:
        msg: " Course Info are: {{ course | dict2items }}"
    
    - name: convert list into map
      vars:
        course:
        - {'key': 'name', 'value': 'ansible'}
        - {'key': 'duration', 'value': '10hrs'}
        - {'key': 'trainer', 'value': 'sivakumar'}
      ansible.builtin.debug:
        msg:  "Course info: {{ course | items2dict }}"

    - name: convert upper to lower
      vars:
        name: "k k d d"
      ansible.builtin.debug:
        msg: "Name : {{ name | upper }} "
    
    - name: convert lower to upper
      vars:
        name: "K K D D"
      ansible.builtin.debug:
        msg: "Name : {{ name | lower }} "

    - name: pringt max and min
      vars:
        numbers: [1,32,74,21,33,3562]
      ansible.builtin.debug:
        msg: " Min numbers are: {{ numbers | min }}, Max Numbers are: {{ numbers | max }}"
    
    - name: Check IP address is valid or not
      vars:
        ip: 19.245.23.23
      ansible.builtin.debug:
        msg: "{{ ip | ansible.utils.ipaddr }}"
  