- name: shell vs command
  hosts: local
  connection: local
  tasks:
    - name: execute ls command using shell
      ansible.builtin.shell: ls -ltr > /tmp/output.txt
    
    - name: execute ls command using command
      ansible.builtin.command: ls -ltr > /tmp/output.txt
      register: command_result
    
    - name: print the output
      ansible.builtin.debug:
        msg: "{{ command_result }}"

