- name: Create EC2 instances and R53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0ea509ad4cba242d7
    sg_id: sg-0e978039cdb6c3057
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    zone: kumardevops.store
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install Python Libraries for server configuration
    ansible.builtin.pip:
      - name: "{{ item }}"
        executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info
  
  - name: print ec2 info
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"
  
  - name: print private IP address
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"

  - name: Create Route53 records
    amazon.aws.route53:
      state: present
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0] }}.{{ private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"
  
  - name: Create Route53 records
    amazon.aws.route53:
      state: present
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0] }}.{{ public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"
    when: item.item == "frontend"