- name: nginx install & enable
  hosts: localhost
  tasks:
  - name: unstall nginx frontend
    ansible.builtin.package:
      name: nginx
      state: present
  - name: nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      