- name: Check status of a servie and email if its down
  hosts: localhost
  tasks:
    - command: service httpd status
      register: result

    - mail:
        to: "kumaro.devops@gmail.com"
        subject: Service Alert
        body: Httpd Service is down
        when: result.stdout.find('down') != -1
        