- name: Ping the server
  hosts: localhost
  vars_files:
    - Course.yaml
  tasks:
    - name: printing the variables from the yaml file
      debug:
        msg: "I am learning new course {{ COURSE }}, with topics {{ topics }} in live {{ live }}, along witgh tools {{ tools }}"

    - name: command for listing variables
      command: ls -ltr
      async: 360
      poll: 20
      register: output

    - name: print the output
      debug:
        msg: "list of current directory: {{ output }}"

    - name: Check status of tasks
      async_status: jid={{ output.ansible_job_id }}
      register: output1
      until: output1.finished
      retries: 30

